
# Metadata

title: CUparkit
email: contact@cuparkit.com
description: >- # this means to ignore newlines until "baseurl:"
  Clemson's parking can be frustrating. Simplify finding a place
  to park your car and save time with CUparkit!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cuparkit.com"
twitter_username: cuparkit
github_username:  cuparkit

# Build Settings

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - github-pages
sass:
  style: compressed
  
# Page Defaults

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
